name: fdeo_env
channels:
  - defaults
dependencies:
  - beautifulsoup4=4.12.2
  - bs4=0.0.1
  - certifi=2023.5.7
  - cftime=1.6.2
  - charset-normalizer=3.2.0
  - cycler=0.11.0
  - fonttools=4.38.0
  - h5py=3.8.0
  - idna=3.4
  - kiwisolver=1.4.4
  - matplotlib=3.5.3
  - netCDF4=1.6.3
  - numpy=1.21.6
  - packaging=23.1
  - Pillow=9.5.0
  - pyhdf=0.10.5
  - pyparsing=3.0.9
  - python-dateutil=2.8.2
  - requests=2.31.0
  - scipy=1.7.3
  - six=1.16.0
  - soupsieve=2.4.1
  - tqdm=4.65.0
  - typing-extensions=4.5.0
  - urllib3=1.26.7
  - gdal=3.6.2